// Generated by Wrangler on Tue Oct 21 2025 11:20:28 GMT-0400 (Eastern Daylight Saving Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  AUTH_GOOGLE_ID: string;
  AUTH_GOOGLE_SECRET: string;
  BETTER_AUTH_SECRET: string;
  DATABASE: D1Database;
}
