name = "cloudflare-saas-stack"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_AUTH_URL = ''
BETTER_AUTH_SECRET = ''


[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = ""
database_id = ""
migrations_dir = "./drizzle"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = ""

[ai]
binding = "AI"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
