name = "cloudflare-saas-stack"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_AUTH_URL = ''
BETTER_AUTH_SECRET = ''
INNGEST_EVENT_KEY = ''
INNGEST_SIGNING_KEY = ''


[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cloudflare-saas-stack-db"
database_id = "07586252-bbff-4c11-a4c9-0390bbe189d1"
migrations_dir = "./drizzle"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cloudflare-saas-stack-bucket"

[ai]
binding = "AI"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
